[workspace]
resolver = "3"
members = ["crates/*"]
package.license = "MIT"
package.edition = "2024"
package.version = "0.10.4"
package.homepage = "https://github.com/anydb-rs/anydb"
package.repository = "https://github.com/anydb-rs/anydb"
package.readme = "docs/README.md"
package.keywords = ["vec", "disk", "database"]
package.categories = ["database"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[workspace.dependencies]
libc = "0.2"
log = "0.4.33"
parking_lot = "0.12.5"
rawdb = { version = "=0.10.4", path = "crates/rawdb" }
rayon = "1.12.0"
tempfile = "3.27.0"
vecdb = { version = "=0.10.4", path = "crates/vecdb" }
vecdb_derive = { version = "=0.10.4", path = "crates/vecdb_derive" }

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"
pre-release-commit-message = "release: v{{version}}"
tag-message = "release: v{{version}}"
